image: docker:latest
services:
  - docker:dind

stages:
  - build
  - release

variables:
  TEST_IMAGE: registry.gitlab.com/nod/ehaber-other-services/news_ingester:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: registry.gitlab.com/nod/ehaber-other-services/news_ingester:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - develmaster
